[workspace]
members = [
  "examples/hello-world/src-tauri",
  "examples/ipc-typed/src-tauri",
  "examples/ipc-typed-with-schema/src-tauri",
  "examples/plugin-clipboard-manager-demo/src-tauri",
  "examples/plugin-dialog-demo/src-tauri",
  "examples/plugin-fs-demo/src-tauri",
  "examples/plugin-http-demo/src-tauri",
  "examples/plugin-log-demo/src-tauri",
  "examples/plugin-notification-demo/src-tauri",
  "examples/plugin-os-demo/src-tauri",
  "examples/plugin-shell-demo/src-tauri",
  "examples/streaming-ipc/src-tauri",
  "examples/window-management/src-tauri",
]
resolver = "2"
