name: tests-schema-types

on:
  push:
    branches: [main]
    paths:
      - "packages/schema/**"
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/tests-schema-types.yml"
      - ".github/workflows/_test-package-types.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/schema/**"
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/_test-package-types.yml"

jobs:
  call:
    uses: ./.github/workflows/_test-package-types.yml
    with:
      package-name: "@rescript-tauri/schema"
      package-path: "packages/schema"
