name: tests-plugin-dialog-types

on:
  push:
    branches: [main]
    paths:
      - "packages/plugin-dialog/**"
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/tests-plugin-dialog-types.yml"
      - ".github/workflows/_test-package-types.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/plugin-dialog/**"
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/_test-package-types.yml"

jobs:
  call:
    uses: ./.github/workflows/_test-package-types.yml
    with:
      package-name: "@rescript-tauri/plugin-dialog"
      package-path: "packages/plugin-dialog"
