name: tests-core-runtime

on:
  push:
    branches: [main]
    paths:
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/tests-core-runtime.yml"
      - ".github/workflows/_test-package-runtime.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/core/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/_test-package-runtime.yml"

jobs:
  call:
    uses: ./.github/workflows/_test-package-runtime.yml
    with:
      package-name: "@rescript-tauri/core"
